/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvSeriesRouteImport } from './routes/tv-series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as BookmarkRouteImport } from './routes/bookmark'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowDetailsIdRouteImport } from './routes/show-details/$id'

const TvSeriesRoute = TvSeriesRouteImport.update({
  id: '/tv-series',
  path: '/tv-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarkRoute = BookmarkRouteImport.update({
  id: '/bookmark',
  path: '/bookmark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowDetailsIdRoute = ShowDetailsIdRouteImport.update({
  id: '/show-details/$id',
  path: '/show-details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmark': typeof BookmarkRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv-series': typeof TvSeriesRoute
  '/show-details/$id': typeof ShowDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmark': typeof BookmarkRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv-series': typeof TvSeriesRoute
  '/show-details/$id': typeof ShowDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmark': typeof BookmarkRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv-series': typeof TvSeriesRoute
  '/show-details/$id': typeof ShowDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmark'
    | '/movies'
    | '/search'
    | '/tv-series'
    | '/show-details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmark'
    | '/movies'
    | '/search'
    | '/tv-series'
    | '/show-details/$id'
  id:
    | '__root__'
    | '/'
    | '/bookmark'
    | '/movies'
    | '/search'
    | '/tv-series'
    | '/show-details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarkRoute: typeof BookmarkRoute
  MoviesRoute: typeof MoviesRoute
  SearchRoute: typeof SearchRoute
  TvSeriesRoute: typeof TvSeriesRoute
  ShowDetailsIdRoute: typeof ShowDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-series': {
      id: '/tv-series'
      path: '/tv-series'
      fullPath: '/tv-series'
      preLoaderRoute: typeof TvSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmark': {
      id: '/bookmark'
      path: '/bookmark'
      fullPath: '/bookmark'
      preLoaderRoute: typeof BookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show-details/$id': {
      id: '/show-details/$id'
      path: '/show-details/$id'
      fullPath: '/show-details/$id'
      preLoaderRoute: typeof ShowDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarkRoute: BookmarkRoute,
  MoviesRoute: MoviesRoute,
  SearchRoute: SearchRoute,
  TvSeriesRoute: TvSeriesRoute,
  ShowDetailsIdRoute: ShowDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
