/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvSeriesRouteImport } from './routes/tv-series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ShowDetailsTypeIdRouteImport } from './routes/show-details/$type/$id'

const TvSeriesRoute = TvSeriesRouteImport.update({
  id: '/tv-series',
  path: '/tv-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowDetailsTypeIdRoute = ShowDetailsTypeIdRouteImport.update({
  id: '/show-details/$type/$id',
  path: '/show-details/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication': typeof AuthenticationRoute
  '/bookmarks': typeof BookmarksRoute
  '/movies': typeof MoviesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/tv-series': typeof TvSeriesRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/show-details/$type/$id': typeof ShowDetailsTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication': typeof AuthenticationRoute
  '/bookmarks': typeof BookmarksRoute
  '/movies': typeof MoviesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/tv-series': typeof TvSeriesRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/show-details/$type/$id': typeof ShowDetailsTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authentication': typeof AuthenticationRoute
  '/bookmarks': typeof BookmarksRoute
  '/movies': typeof MoviesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/tv-series': typeof TvSeriesRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/show-details/$type/$id': typeof ShowDetailsTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication'
    | '/bookmarks'
    | '/movies'
    | '/reset-password'
    | '/search'
    | '/tv-series'
    | '/profile/$username'
    | '/show-details/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authentication'
    | '/bookmarks'
    | '/movies'
    | '/reset-password'
    | '/search'
    | '/tv-series'
    | '/profile/$username'
    | '/show-details/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/authentication'
    | '/bookmarks'
    | '/movies'
    | '/reset-password'
    | '/search'
    | '/tv-series'
    | '/profile/$username'
    | '/show-details/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationRoute: typeof AuthenticationRoute
  BookmarksRoute: typeof BookmarksRoute
  MoviesRoute: typeof MoviesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  TvSeriesRoute: typeof TvSeriesRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ShowDetailsTypeIdRoute: typeof ShowDetailsTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-series': {
      id: '/tv-series'
      path: '/tv-series'
      fullPath: '/tv-series'
      preLoaderRoute: typeof TvSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show-details/$type/$id': {
      id: '/show-details/$type/$id'
      path: '/show-details/$type/$id'
      fullPath: '/show-details/$type/$id'
      preLoaderRoute: typeof ShowDetailsTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationRoute: AuthenticationRoute,
  BookmarksRoute: BookmarksRoute,
  MoviesRoute: MoviesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  TvSeriesRoute: TvSeriesRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ShowDetailsTypeIdRoute: ShowDetailsTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
